configfile: "config/config.yaml"

include: "workflow/rules/rules.smk"

rule all:
    input:
        "done__busco"

rule hard_reset:
    shell:
        """
        rm logs/*
        rm -rdf 0*_*/*
        """
